name: ChrisHub

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          targetBranch: production
          baseHref: /chrishub/
          customArgs: --web-renderer canvaskit
